#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

# Setting up and starting the helper processes
STATS_HELPER=git.hxhelm.sketchybar-stats
source "$HOME/.config/sketchybar/rs-helper/stats.sh"

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="FiraCode Nerd Font Propo"
PADDINGS=4

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

bar=(
  color=$TRANSPARENT
  height=32
  shadow=off
  position=top
  sticky=on
  padding_right=0
  padding_left=0
  corner_radius=9
  y_offset=4
  margin=8
  notch_width=0
  hidden=on
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:14.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}" updates=when_shown

# Left
source "$ITEM_DIR/apple.sh"
sketchybar --add item front_app left                               \
           --set front_app       script="$PLUGIN_DIR/front_app.sh" \
                                 icon.drawing=off                  \
           --subscribe front_app front_app_switched

# Center
# source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/stats/item.sh"
# source "$ITEM_DIR/volume.sh"

source "$ITEM_DIR/hide.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
